# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-30 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('special_icon', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='POIType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.TextField()),
                ('display', models.IntegerField()),
                ('special_fields', models.BooleanField()),
            ],
        ),
    ]
