# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-30 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapmaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='pos_x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='pos_y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
